# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Alessandro Arrichiello - Resume webpage'
tagline:          'Sales Engineer, Solution Architect, Public Speaker'
description:      ''
url:              https://alezzandro.com
baseurl:          /

author:
  name:           'Alessandro Arrichiello'
  url:            https://www.linkedin.com/in/alessandroarrichiello/

paginate:         5

# Custom vars
version:          '2.1.0'

github:
  repo:           https://github.com/alezzandro
